export const TARGET_ROLES = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Engineering Manager",
  "Scrum Master",
  "Agile Delivery Manager",
  "Agile Coach",
  "Delivery Manager",
  "Program Manager",
  "Technical Program Manager",
  "Product Manager",
  "Senior Product Manager",
  "Associate Product Manager",
  "Business Analyst",
  "Solution Architect",
  "Technical Architect",
  "Cloud Architect",
  "UI/UX Designer",
  "Product Designer",
  "QA Lead",
  "QA Engineer",
  "SDET",
  "Test Automation Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Cloud Engineer",
  "Cybersecurity Engineer",
  "Security Analyst",
  "Network Engineer",
  "Systems Engineer",
  "Java Developer",
  "Spring Boot Developer",
  ".Net Developer",
  "C# Developer",
  "Python Developer",
  "Node.js Developer",
  "Golang Developer",
  "PHP Developer",
  "Ruby on Rails Developer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "React Native Developer",
  "Full Stack Developer",
  "Back End Developer",
  "Data Analyst",
  "BI Analyst",
  "Analytics Engineer",
  "Project Manager",
  "Data Engineer",
  "Big Data Engineer",
  "Machine Learning Engineer",
  "AI/ML Engineer",
  "MLOps Engineer",
  "NLP Engineer",
  "Data Scientist",
  "Prompt Engineer",
  "GenAI Engineer",
  "Blockchain Developer",
  "Salesforce Developer",
  "SAP Consultant",
  "Front End Developer",
  "React Developer",
  "Angular Developer",
  "Vue.js Developer",
] as const;
